Reader
dVaGaymer/minishell pull request #31
Opened 2022-10-10 10:25 UTC by dVaGaymer

2022-10-10 11:06 UTC, arikhativa requested changes
nice it looks good :)
there are a few small changes

2022-10-10 11:06 UTC, arikhativa commented on include/macro.h
> +# define DQUOTE_PROMPT		"dquote> "
i think there should be a 'quote' promt
you dont need to do that in this PR, you can create a new PR for that

![image](https://user-images.githubusercontent.com/49197152/194850523-56b52810-532e-4507-8fd4-366d818b7dca.png)

2022-10-10 11:06 UTC, arikhativa commented on include/reader.h
> +int            	is_special(char *str);
int -> t_bool

2022-10-10 11:06 UTC, arikhativa commented on include/reader.h
> +t_error_code	reader(char ***ret);
the name is not clear enough, add something to reader_'ACTION'()

2022-10-10 11:06 UTC, arikhativa commented on include/reader.h
> +t_bool			quote_is_closed(char *str);
quote_is_closed -> is_quote_closed

2022-10-10 11:06 UTC, arikhativa commented on src/reader/reader.c
> +	char	i;
why char?
can 'i' be bigger then 127?

2022-10-10 11:06 UTC, arikhativa commented on src/reader/reader.c
> +	char	i;
same 'char i'

2022-10-10 11:06 UTC, arikhativa commented on src/reader/reader.c
> +t_error_code	reader_from_arg(int argc, char **argv)
who is using this func?

2022-10-10 11:06 UTC, arikhativa commented on src/reader/reader.c
> +	dquote(&line);
I think this func should have a better name
but im not sure

2022-10-10 11:06 UTC, arikhativa commented on src/reader/reader_split_smart.c
> +t_error_code	reader_split_arg(char *str, char ***ret)
who is using this?

2022-10-10 11:06 UTC, arikhativa commented on unit_test/reader/reader.t.c
> +void	test_reader(void)
a very cool test!

2022-10-10 11:06 UTC, arikhativa commented on unit_test/reader/reader.t.c
> +	err = allocate_words("Alvaro Lopez <Gomez>> and|Yoav|", &tab, 9);
maybe add somthing like this:
CU_ASSERT_STRING_EQUAL(tab[0], "Alvaro")

2022-10-11 09:38 UTC, dVaGaymer commented on include/reader.h
> +t_error_code	reader(char ***ret);
reader_get_tab() ???

2022-10-11 09:38 UTC, dVaGaymer commented on src/reader/reader.c
> +	char	i;
I changed i: char -> size_t

2022-10-11 09:40 UTC, dVaGaymer commented on src/reader/reader.c
> +	dquote(&line);
dquote -> close_opened_quote

2022-10-11 09:49 UTC, closed without merging