Expander
dVaGaymer/minishell pull request #59
Opened 2022-11-02 12:54 UTC by dVaGaymer

2022-11-02 15:17 UTC, arikhativa requested changes
some small chnages

2022-11-02 15:17 UTC, arikhativa commented on include/error_code.h
> +/*   Updated: 2022/11/02 12:20:29 by al7aro           ###   ########.fr       */
redundant change

2022-11-02 15:17 UTC, arikhativa commented on resources/run_minishell_no_env.c
> +/*   Updated: 2022/11/01 22:22:17 by r3dc4t           ###   ########.fr       */
redundant

2022-11-02 15:17 UTC, arikhativa commented on src/expander/expander.c
> +static int	get_error_var(t_shell_op sp, char **ret)
it is better to pass objects as pointers since the obj can be very big and slow the stack call operation

2022-11-02 15:17 UTC, arikhativa commented on src/expander/expander.c
> +	return (1);
why ret value?

2022-11-02 15:17 UTC, arikhativa commented on src/reader/reader_files.c
> +	tmp = line;
is this needed?

2022-11-20 14:35 UTC, dVaGaymer commented on src/reader/reader_files.c
> +	tmp = line;
You mean this function?

2022-11-20 15:33 UTC, arikhativa requested changes
looks good :)
there are a few changes

also i think there is a bug with:
`echo '$SHLVL'` -> "2"
i'll send on slack

2022-11-20 15:33 UTC, arikhativa commented on include/cmd.h
> +/*   Updated: 2022/11/17 01:41:57 by alopez-g         ###   ########.fr       */
redundant change

2022-11-20 15:33 UTC, arikhativa commented on src/expander/expander.c
> +// TODO CHECK HUGE AMMOUNT OF LEAKS
do you want to keep these comments?

2022-11-20 15:33 UTC, arikhativa commented on src/expander/expander.c
> +		*(ret + i) = str_append_char((ret + i), '\"', FALSE);
" -> macro for qoutes

2022-11-20 15:33 UTC, arikhativa commented on src/expander/expander.c
> +	if ('?' == *(str + 1))
? -> macro

2022-11-20 15:33 UTC, arikhativa commented on src/expander/expander_utils.c
> +		|| MINUS_CHAR == c
why MINUS_CHAR?
i think you can use ft_isalpha()

2022-11-20 15:33 UTC, arikhativa commented on src/main/main.c
> +	err = read_func(sp, &(sp->input));
i think this:
read_func(sp, &(sp->input));
should be:
read_func(sp);

2022-11-21 10:22 UTC, arikhativa requested changes
check what are the valid env keys

2022-11-30 14:25 UTC, arikhativa approved these changes

2022-11-30 14:26 UTC, merged